#ifndef __ERYAPIXEdialogERYACalculator__
#define __ERYAPIXEdialogERYACalculator__

/**
@file
Subclass of dialogERYACalculator, which is generated by wxFormBuilder.
*/

#include "ERYAPIXE.h"

//// end generated include

/** Implementing dialogERYACalculator */
class ERYAPIXEdialogERYACalculator : public dialogERYACalculator
{
	protected:
		// Handlers for dialogERYACalculator events.
		void OnAcos( wxCommandEvent& event );
		void OnAsin( wxCommandEvent& event );
		void OnAtan( wxCommandEvent& event );
		void OnFxvar( wxCommandEvent& event );
		void OnLeftParenthesis( wxCommandEvent& event );
		void OnRightParenthesis( wxCommandEvent& event );
		void OnSqrt( wxCommandEvent& event );
		void OnPower( wxCommandEvent& event );
		void OnClearInput( wxCommandEvent& event );
		void OnLess( wxCommandEvent& event );
		void OnMore( wxCommandEvent& event );
		void OnAcosh( wxCommandEvent& event );
		void OnAsinh( wxCommandEvent& event );
		void OnAtanh( wxCommandEvent& event );
		void OnFyvar( wxCommandEvent& event );
		void OnSeven( wxCommandEvent& event );
		void OnEight( wxCommandEvent& event );
		void OnNine( wxCommandEvent& event );
		void OnPlus( wxCommandEvent& event );
		void OnClearOutput( wxCommandEvent& event );
		void OnCos( wxCommandEvent& event );
		void OnSin( wxCommandEvent& event );
		void OnTan( wxCommandEvent& event );
		void OnFxmin( wxCommandEvent& event );
		void OnFour( wxCommandEvent& event );
		void OnFive( wxCommandEvent& event );
		void OnSix( wxCommandEvent& event );
		void OnMinus( wxCommandEvent& event );
		void OnComma( wxCommandEvent& event );
		void OnCosh( wxCommandEvent& event );
		void OnSinh( wxCommandEvent& event );
		void OnTanh( wxCommandEvent& event );
		void OnFxmax( wxCommandEvent& event );
		void OnOne( wxCommandEvent& event );
		void OnTwo( wxCommandEvent& event );
		void OnThree( wxCommandEvent& event );
		void OnTimes( wxCommandEvent& event );
		void OnColon( wxCommandEvent& event );
		void OnExp( wxCommandEvent& event );
		void OnLog( wxCommandEvent& event );
		void OnLn( wxCommandEvent& event );
		void OnFunctionVar( wxCommandEvent& event );
		void OnZero( wxCommandEvent& event );
		void OnDecimal( wxCommandEvent& event );
		void OnExponential( wxCommandEvent& event );
		void OnDivide( wxCommandEvent& event );
		void OnReturn( wxCommandEvent& event );
        void OnHelp( wxCommandEvent& event );
        void OnBackSpace( wxCommandEvent& event );
        void OnAssign( wxCommandEvent& event );
        void OnDisplayProgram( wxCommandEvent& event );
        void OnDisplayAnswer( wxCommandEvent& event );
        void OnVectorMacro( wxCommandEvent& event );
		void OnSetDecimals( wxCommandEvent& event );
		void OnInputVariable( wxCommandEvent& event );

                // Internal variables
                double LastAns;
                int DecimalPrecision;
                std::vector<double> LastVector;
                wxString LastVariables;
    private:
        wxString GetConversion(double Var, bool Sci);

	public:
		/** Constructor */
		ERYAPIXEdialogERYACalculator( wxWindow* parent );
	//// end generated class members



};

#endif // __ERYAPIXEdialogERYACalculator__
