/***************************************************************
 * Name:      ERYAPIXEdialogAddDatabase.h
 * Purpose:   ERYA Database Editor implementation classes
 * Author:    Vasco Manteigas (vm.manteigas@campus.fct.utl.pt)
 * Created:   2015-12-01
 * Copyright: Grupo de Reacoes Nucleares - LIBPHYS
 * License:
 **************************************************************/

#ifndef __ERYAPIXEdialogAddDatabase__
#define __ERYAPIXEdialogAddDatabase__

/**
@file
Subclass of dialogAddDatabase, which is generated by wxFormBuilder.
*/

#include "ERYAPIXE.h"
//// end generated include

/** Implementing dialogAddDatabase */
class ERYAPIXEdialogAddDatabase : public dialogAddDatabase
{
	private:
	int Units,Angles,Profile;
	bool IgnoreLine;
	wxString infoRemark;
	protected:
		// Handlers for dialogAddDatabase events.
		void OnDatabaseSelect( wxGridRangeSelectEvent& event );
		void OnImportR33( wxCommandEvent& event );
		void OnExportR33( wxCommandEvent& event );
		void OnDatabaseCopy( wxCommandEvent& event );
		void OnDatabasePaste( wxCommandEvent& event );
		void OnEditClear( wxCommandEvent& event );
		void OnEditSave( wxCommandEvent& event );
		void OnEditCancel( wxCommandEvent& event );
		void OnEditHelp( wxCommandEvent& event );
	public:
		/** Constructor */
		ERYAPIXEdialogAddDatabase( wxWindow* parent);
		void SetSelectUnit(int SigmaUnit){Units = SigmaUnit; return;};
	    void SetSelectAngle(int SigmaAngle){Angles = SigmaAngle; return;};
	    void SetSelectMode(int SigmaProfile){Profile = SigmaProfile; return;};
	    void SetIgnoreInvalidLine(bool ParserErrorDisable){IgnoreLine = ParserErrorDisable; return;};
	    void SetRemark(wxString &info){infoRemark = info; return;};

	//// end generated class members




};

#endif // __ERYAPIXEdialogAddDatabase__
