/***************************************************************
 * Name:      ERYAPIXEdialogDetectorSetup.h
 * Purpose:   ERYA Detector Setup implementation classes
 * Author:    Vasco Manteigas (vm.manteigas@campus.fct.utl.pt)
 * Created:   2015-12-01
 * Copyright: Grupo de Reacoes Nucleares - LIBPHYS
 * License:
 **************************************************************/

#ifndef __ERYAPIXEdialogDetectorSetup__
#define __ERYAPIXEdialogDetectorSetup__

/**
@file
Subclass of dialogDetectorSetup, which is generated by wxFormBuilder.
*/

#include "ERYAPIXE.h"
#include "ParserLibrary.h"
#include "FileLibrary.h"
#include "DatabaseLibrary.h"

//// end generated include

/** Implementing dialogDetectorSetup */
class ERYAPIXEdialogDetectorSetup : public dialogDetectorSetup
{
	protected:
		// Handlers for dialogDetectorSetup events.
		void OnEficiencySelect( wxGridRangeSelectEvent& event );
       void OnEficiencyCopy( wxCommandEvent& event );
		void OnEficiencyPaste( wxCommandEvent& event );
		void OnEficiencyLoad( wxCommandEvent& event );
		void OnEficiencySave( wxCommandEvent& event );
		void OnEficiencyClear( wxCommandEvent& event );
		void OnEficiencyOK( wxCommandEvent& event );
		void OnEficiencyCancel( wxCommandEvent& event );
		void OnEficiencyHelp( wxCommandEvent& event );
	public:
		/** Constructor */
		ERYAPIXEdialogDetectorSetup( wxWindow* parent );
	//// end generated class members



};

#endif // __ERYAPIXEdialogDetectorSetup__
