/***************************************************************
 * Name:      ERYAPIXEdialogSetup.h
 * Purpose:   ERYA Config Editor headers
 * Author:    Vasco Manteigas (vm.manteigas@campus.fct.utl.pt)
 * Created:   2016-12-01
 * Copyright: Grupo de Reacoes Nucleares - LIBPHYS
 * License:
 **************************************************************/
 
#ifndef ERYAPIXEDIALOGSETUP_H_INCLUDED
#define ERYAPIXEDIALOGSETUP_H_INCLUDED

/**
@file
Subclass of dialogSetup, which is generated by wxFormBuilder.
*/

#include "ERYAPIXE.h"

//// end generated include

/** Implementing dialogSetup */
class ERYAPIXEdialogSetup : public dialogSetup
{
	protected:
		// Handlers for dialoghelp events.
		void OnDefaultSave( wxCommandEvent& event );
		void OnDefaultReset( wxCommandEvent& event );
		void OnDefaultDelete( wxCommandEvent& event );
		void OnDefaultQuit( wxCommandEvent& event );
	public:
		/** Constructor */
        ERYAPIXEdialogSetup( wxWindow* parent );
	//// end generated class members


};


#endif // ERYAPIXEDIALODSETUP_H_INCLUDED