#ifndef __ERYAPIXEdialogRemark__
#define __ERYAPIXEdialogRemark__

/**
@file
Subclass of dialogRemark, which is generated by wxFormBuilder.
*/

#include "ERYAPIXE.h"

//// end generated include

/** Implementing dialogRemark */
class ERYAPIXEdialogRemark : public dialogRemark
{
	protected:
		// Handlers for dialogRemark events.
		void OnRemarkSave( wxCommandEvent& event );
		void OnRemarkClear( wxCommandEvent& event );
		void OnRemarkQuit( wxCommandEvent& event );
	public:
		/** Constructor */
		ERYAPIXEdialogRemark( wxWindow* parent, wxString info, int n );
		ERYAPIXEdialogRemark( wxWindow* parent );
	private:
        int FlagValue;
	//// end generated class members

};

#endif // __ERYAPIXEdialogRemark__
