/***************************************************************
 * Name:      ERYAPIXEdialogDatabaseManager.h
 * Purpose:   ERYA Database Manager implementation classes
 * Author:    Vasco Manteigas (vm.manteigas@campus.fct.utl.pt)
 * Created:   2015-12-01
 * Copyright: Grupo de Reacoes Nucleares - LIBPHYS
 * License:
 **************************************************************/

#ifndef __ERYAPIXEdialogDatabaseManager__
#define __ERYAPIXEdialogDatabaseManager__

/**
@file
Subclass of dialogDatabaseManager, which is generated by wxFormBuilder.
*/

#include "ERYAPIXE.h"
#include "DatabaseLibrary.h"

//// end generated include

/** Implementing dialogDatabaseManager */
class ERYAPIXEdialogDatabaseManager : public dialogDatabaseManager
{
    private:
         wxString infoRemark;
	protected:
		// Handlers for dialogDatabaseManager events.
		void OnElementName( wxCommandEvent& event );
		void OnGammaPeak( wxCommandEvent& event );
		void OnDatabaseAdd( wxCommandEvent& event );
		void OnDatabaseEdit( wxCommandEvent& event );
		void OnDatabaseRemove( wxCommandEvent& event );
		void OnDatabaseClear( wxCommandEvent& event );
		void OnDatabaseLoad( wxCommandEvent& event );
		void OnDatabaseSave( wxCommandEvent& event );
		void OnDatabaseCancel( wxCommandEvent& event );
		void OnDatabaseHelp( wxCommandEvent& event );
	public:
		/** Constructor */
		ERYAPIXEdialogDatabaseManager( wxWindow* parent );
		bool WriteElement; // Write flag
        bool ChangeElement; //Edit flag
		ElementDatabase EditElement; // Local temporary variable
		ElementDatabaseArray MainDatabase; // Current opened database
		void StoreElement(ElementDatabase ThisElement) { EditElement = ThisElement; }  // Safe storing method
        void GetElement(ElementDatabase& ThisElement) {ThisElement = EditElement; return;} // Safe retrieving method
		void SaveElement(bool FlagElement) { WriteElement = FlagElement; }  // Get save flag method
        void ModifyElement(bool& FlagEdit) { FlagEdit = ChangeElement; return;} // Get edit flag  method
        void SetRemark(wxString &info){infoRemark = info; MainDatabase.SetInfo(infoRemark); return;};

	//// end generated class members

};


#endif // __ERYAPIXEdialogDatabaseManager__
