/***************************************************************
 * Name:      ERYAPIXEdialogXlsxDataImport.h
 * Purpose:   ERYA Xlsx Data Import Tool implementation classes
 * Author:    Vasco Manteigas (vm.manteigas@campus.fct.utl.pt)
 * Created:   2017-01-01
 * Copyright: Grupo de Reacoes Nucleares - LIBPHYS
 * License:
 **************************************************************/

#ifndef ERYAPIXEDIALOGXLSXDATAIMPORT_H_INCLUDED
#define ERYAPIXEDIALOGXLSXDATAIMPORT_H_INCLUDED

/**
@file
Subclass of dialogXlsxDataImport, which is generated by wxFormBuilder.
*/

#include "ERYAPIXE.h"
//// end generated include

/** Implementing dialogXlsxDataImport */
class ERYAPIXEdialogXlsxDataImport : public dialogXlsxDataImport
{
	protected:
		// Handlers for dialogAddDatabase events.
	void OnDataImportValidate( wxCommandEvent& event );
    void OnDataImportAbort( wxCommandEvent& event );
    void OnDataImportReset( wxCommandEvent& event );
    void OnDataImportHelp( wxCommandEvent& event );
	public:
		/** Constructor */
		ERYAPIXEdialogXlsxDataImport( wxWindow* parent);

	//// end generated class members




};

#endif // ERYAPIXEDIALOGXLSXDATAIMPORT_H_INCLUDED
