/***************************************************************
 * Name:      ERYAPIXEdialogHelp.h
 * Purpose:   ERYA Fitting Tuning applet declaration
 * Author:    Vasco Manteigas (vm.manteigas@campus.fct.utl.pt)
 * Created:   2015-12-01
 * Copyright: Grupo de Reacoes Nucleares - LIBPHYS
 * License:
 **************************************************************/


#ifndef ERYAPIXEDIALOGADVANCED_H_INCLUDED
#define ERYAPIXEDIALOGADVANCED_H_INCLUDED

/**
@file
Subclass of dialogAdvancedFit, which is generated by wxFormBuilder.
*/

#include "ERYAPIXE.h"

//// end generated include

/** Implementing dialogAdvancedFit */
class ERYAPIXEdialogAdvanced : public dialogAdvancedFit
{
	protected:
		// Handlers for dialoghelp events.
		void OnAdvancedOK( wxCommandEvent& event );
		void OnAdvancedCancel( wxCommandEvent& event );
		void OnAdvancedReset( wxCommandEvent& event );
		void OnAdvancedHelp( wxCommandEvent& event );
	public:
		/** Constructor */
		ERYAPIXEdialogAdvanced( wxWindow* parent );
	//// end generated class members


};


#endif // ERYAPIXEDIALOGADVANCED_H_INCLUDED
