#ifndef __ERYAPIXEwizardFirstRun__
#define __ERYAPIXEwizardFirstRun__

/**
@file
Subclass of wizardFirstRun, which is generated by wxFormBuilder.
*/

#include "ERYAPIXE.h"

//// end generated include

/** Implementing wizardFirstRun */
class ERYAPIXEwizardFirstRun : public wizardFirstRun
{
	protected:
		// Handlers for wizardFirstRun events.
		void OnFirstRunCancel( wxWizardEvent& event );
		void OnFirstRunFinish( wxWizardEvent& event );
	public:
		/** Constructor */
		ERYAPIXEwizardFirstRun( wxWindow* parent );
	//// end generated class members




};

#endif // __ERYAPIXEwizardFirstRun__
